### ISSUE TITLE
Can you do a demmo

### ISSUE THREAD

**Issue by biz131** [jblanked/WebCrawler-FlipperZero#1]
I eliev that I am installing the firmware worng ad it keeps saying saving data, please wait. I think I am doing something wrong

**Comment by jblanked** [comment]
Thank you for taking the time to review and use the app.

You may be having issues due to the differences between the v0.1 flash and v0.2 flash. Unfortunately, you'll need to wait until v0.2 is released on the app store. I submitted the latest version (v0.2) to the official App Store yesterday and updated the firmware instructions. Once available, try again and let me know if you still have issues. 

After installing version 0.2, you'll no longer have flash firmware connection issues between versions.

**Comment by jblanked** [comment]
> I eliev that I am installing the firmware worng ad it keeps saying saving data, please wait. I think I am doing something wrong

Thank you for your patience! Version 0.2 just got released on the App Store (https://lab.flipper.net/apps/web_crawler) and I just uploaded v0.3 to Github. I also created a Javascript library for the FlipperHTTP flash.

**Comment by biz131** [comment]
So I was able to get data but noticed the file naming and file type isnt always coonsistant. If I change it, it doesnt always replicate when reviewing the files on my flipper. I tried to get the file to save as an html file but it did it as a txt instead. It does sometimes work.

**Comment by jblanked** [comment]
Screenshot your files and can you tell me step-by-step what you did to get those results?

The received_data.txt file will never change. When you rename or change the file extension, it will create a duplicate of the received_data.txt and apply the change to the duplicate. However if you click Delete File, it will delete both your customize file name and the original received_data.txt

Also, version 0.3 is available on the App Store 🔥
