### ISSUE TITLE
App downloaded from the store stuck on saving state screen.

### ISSUE THREAD

**Issue by MassivDash** [jblanked/WebCrawler-FlipperZero#2]
Hello 

Bug Description: 
App gets stuck on the saving state screen, crashes or slows down the firmware.
Checked the logs they indicate connection to the wifi dev board is broken, logs display connection timeout errors. 

Steps to reproduce
- follow the flashing tutorial
- download the app through the store (ios compnanion app in my case)
- configure
- run
- observe being stucked

Notes: 

Ive cloned the project and lunched the current version through ufbt, and it worked correctly, i was able to scrape google.com and some very basic website like this one https://expresstest.spaceout.pl/, but this one https://astrox.spaceout.pl/ which its a static website fails, and basically every "bigger" website results in failure. Any ways how that could be increased ?

**Comment by jblanked** [comment]
Thank you for taking the time to review and use the app.

The issue is due to differences between the v0.1 and v0.2 firmware. Unfortunately, you’ll need to wait until v0.2 is released on the App Store. I submitted the latest version (v0.2) to the official App Store yesterday and updated the firmware instructions. Once it’s available, try again, and let me know if you still encounter any issues.

After installing version 0.2, you should no longer experience firmware connection issues between versions.

**Post Edit:** I just saw your notes.

A future update will address that, but it could be one of two reasons for the current issue:
1. The website requires JavaScript. 
2. The returned data is too large, causing the Dev Board serial to time out.

**Comment by MassivDash** [comment]
Any chance you will upload / open source the the flipper-web-dev board custom flash ?

**Comment by jblanked** [comment]
Yes, I plan to release that after it's completed. Version 0.4 of the Web Crawler app should include the final version of the flash. I'll be welcoming contributors after that 🔥

For now, you can utilize the flipper_http.h file for utilizing the flash within Flipper Zero apps. I also plan to create JavaScript and Python libraries for the flash.

**Comment by jblanked** [comment]
Thank you for your patience! Version 0.2 just got released on the App Store (https://lab.flipper.net/apps/web_crawler) and I just uploaded v0.3 to Github. I also created a Javascript library for the FlipperHTTP flash.

**Comment by jblanked** [comment]
Just posted the source code! I would love your contributions: https://github.com/jblanked/WebCrawler-FlipperZero/tree/main/assets/FlipperHTTP
